const categoryData={
 home:{title:'Home & desktop décor',short:'home décor',image:'assets/categories/home.jpg',alt:'Home and desktop décor product direction',materials:['Ceramic','Resin','Wood','Iron & metal']},
 gifts:{title:'Crafts, gifts & collectibles',short:'gifts and collectibles',image:'assets/categories/gifts-optimized.jpg',alt:'Crafts, gifts and collectible product direction',materials:['Ceramic','Resin','Wood','Textile','Iron & metal']},
 habitat:{title:'Aquarium & reptile décor',short:'habitat décor',image:'assets/categories/habitat.jpg',alt:'Aquarium and reptile décor product direction',materials:['Resin','Ceramic']},
 garden:{title:'Garden décor & planters',short:'garden décor',image:'assets/categories/garden-optimized.jpg',alt:'Garden décor and planter product direction',materials:['Resin','Ceramic','Wood','Iron & metal']},
 bathroom:{title:'Bathroom accessories & storage',short:'bathroom accessories',image:'assets/categories/organizer.jpg',alt:'Bathroom accessories and storage product direction',materials:['Ceramic','Resin','Wood','Iron & metal']},
 lifestyle:{title:'Lifestyle & seasonal',short:'lifestyle collection',image:'assets/categories/lifestyle.jpg',alt:'Lifestyle and seasonal product direction',materials:['Textile','Wood','Ceramic','Resin','Iron & metal']}
};
function updateDirection(key,scroll=false){const data=categoryData[key]||categoryData.home;const select=document.querySelector('#guide-category');if(!select)return;if(select.value!==key)select.value=key;document.querySelector('#guide-title').textContent=data.title;const img=document.querySelector('#guide-image');img.src=data.image;img.alt=data.alt;document.querySelector('#guide-materials').innerHTML=data.materials.map(m=>`<span>${m}</span>`).join('');const cta=document.querySelector('#guide-cta');cta.textContent=`Start a ${data.short} brief ↗`;cta.href=`index.html?category=${key}#brief`;if(scroll)history.replaceState(null,'',`${location.pathname}?category=${key}#direction`);if(scroll)document.querySelector('#direction').scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth'});}
document.querySelectorAll('[data-select-category]').forEach(link=>link.addEventListener('click',e=>{e.preventDefault();updateDirection(link.dataset.selectCategory,true)}));
document.querySelector('#guide-category')?.addEventListener('change',e=>updateDirection(e.target.value));
document.querySelectorAll('[data-material]').forEach(button=>button.addEventListener('click',()=>{const value=button.dataset.material;let count=0;document.querySelectorAll('[data-materials]').forEach(card=>{card.hidden=value!=='all'&&!card.dataset.materials.split('|').includes(value);if(!card.hidden)count++});document.querySelectorAll('[data-material]').forEach(b=>b.setAttribute('aria-pressed',String(b===button)));document.querySelector('#category-count').textContent=`${count} product ${count===1?'category':'categories'}`}));
const initial=new URLSearchParams(location.search).get('category');updateDirection(categoryData[initial]?initial:'home');
