(()=>{
const categories={home:'Home décor & collectibles',kitchen:'Kitchen & tabletop',lighting:'Lighting & ambience',wall:'Wall décor & mirrors',bath:'Bath & organisation',garden:'Garden & planters',habitat:'Aquarium & reptile',seasonal:'Seasonal & gifting'};
const enquiryContext=()=>{const params=new URLSearchParams(location.search);return {source_page:location.pathname||'/',submitted_at:new Date().toISOString(),utm_source:params.get('utm_source')||'',utm_medium:params.get('utm_medium')||'',utm_campaign:params.get('utm_campaign')||''}};
const siteHeader=document.querySelector('.site-header');
if(siteHeader){const navigation=siteHeader.querySelector('nav');if(navigation){if(!navigation.id)navigation.id='site-navigation';const menuButton=document.createElement('button');menuButton.type='button';menuButton.className='menu-toggle';menuButton.setAttribute('aria-controls',navigation.id);menuButton.setAttribute('aria-expanded','false');menuButton.setAttribute('aria-label','Open menu');menuButton.innerHTML='<span></span><span></span><span></span>';siteHeader.insertBefore(menuButton,navigation);const setMenu=open=>{siteHeader.classList.toggle('menu-open',open);menuButton.setAttribute('aria-expanded',String(open));menuButton.setAttribute('aria-label',open?'Close menu':'Open menu')};menuButton.addEventListener('click',()=>setMenu(!siteHeader.classList.contains('menu-open')));navigation.addEventListener('click',event=>{if(event.target.closest('a'))setMenu(false)});document.addEventListener('keydown',event=>{if(event.key==='Escape')setMenu(false)});}}
document.querySelectorAll('.motion-toggle').forEach(button=>button.addEventListener('click',()=>{const paused=button.getAttribute('aria-pressed')!=='true';button.setAttribute('aria-pressed',String(paused));button.textContent=paused?'Resume logo motion':'Pause logo motion';button.closest('.brand-experience').querySelector('.logo-marquee').classList.toggle('is-paused',paused)}));
function applyBrief(data){if(data.topic&&data.topic!=='Commerce AI'&&!data.brief)data.brief='I would like to discuss '+data.topic.toLowerCase()+'.';const form=document.querySelector('#direction-form, #workflow-form');if(!form)return;['name','email','company','market','quantity','project_stage','brief'].forEach(key=>{const el=form.elements.namedItem(key);if(el&&data[key]){el.value=data[key];el.dispatchEvent(new Event('input',{bubbles:true}))}});const direction=document.querySelector('#product-direction');if(direction&&data.category){const label=categories[data.category];const option=[...direction.options].find(o=>o.textContent===label||o.value===label);if(option)direction.value=option.value}if(document.querySelector('#workflow-form')){const workflow=document.querySelector('#brief-workflow');if(workflow&&data.topic)workflow.value=data.topic;const brief=document.querySelector('#brief-today');if(brief&&data.brief)brief.value=data.brief;}}
try{const raw=sessionStorage.getItem('able_enquiry_handoff');if(raw){applyBrief(JSON.parse(raw));sessionStorage.removeItem('able_enquiry_handoff')}}catch{}
const query=new URLSearchParams(location.search);if(document.querySelector('#direction-form')){if(query.has('category'))applyBrief({category:query.get('category')});if(query.get('topic')==='manufacturing'){const field=document.querySelector('#direction-form [name=brief]');if(field&&!field.value)field.value='I would like to discuss manufacturing capability, samples and production requirements.'}}

const images=[...document.querySelectorAll('.work-image')];if(images.length){const dialog=document.createElement('dialog');dialog.className='work-preview';dialog.innerHTML='<button type="button" class="preview-close" aria-label="Close image preview">×</button><img alt=""><p></p>';document.body.append(dialog);const close=()=>dialog.close();dialog.querySelector('button').addEventListener('click',close);dialog.addEventListener('click',e=>{if(e.target===dialog)close()});images.forEach(w=>{const img=w.querySelector('img');const button=document.createElement('button');button.type='button';button.className=w.className;button.setAttribute('aria-label','Enlarge '+img.alt);while(w.firstChild)button.append(w.firstChild);w.replaceWith(button);button.addEventListener('click',()=>{dialog.querySelector('img').src=img.src;dialog.querySelector('img').alt=img.alt;dialog.querySelector('p').textContent=img.alt;dialog.showModal()})})}
const productionRail=document.querySelector('.production-rail');
if(productionRail){const move=direction=>productionRail.scrollBy({left:direction*Math.min(productionRail.clientWidth*.8,620),behavior:'smooth'});document.querySelector('[data-rail-prev]')?.addEventListener('click',()=>move(-1));document.querySelector('[data-rail-next]')?.addEventListener('click',()=>move(1));}
const launcher=document.createElement('button');launcher.className='ask-able-launcher';launcher.textContent='Ask Able ↗';launcher.setAttribute('aria-expanded','false');launcher.setAttribute('aria-controls','ask-able-panel');
const panel=document.createElement('section');panel.id='ask-able-panel';panel.className='ask-able-panel';panel.hidden=true;panel.setAttribute('role','dialog');panel.setAttribute('aria-label','Ask Able project enquiry');panel.innerHTML=`<div class="ask-head"><h2>Ask Able</h2><button type="button" class="ask-close" aria-label="Close Ask Able">×</button></div><p class="ask-intro">What are you working on? Build a short local brief for our sourcing, factory or tech team.</p><form id="ask-able-form"><div class="ask-step" data-step="1"><div class="ask-topics"><button type="button" data-topic="Product sourcing" aria-pressed="true">Find products</button><button type="button" data-topic="Product development" aria-pressed="false">Develop a product</button><button type="button" data-topic="Manufacturing" aria-pressed="false">Factory & production</button><button type="button" data-topic="Commerce AI" aria-pressed="false">Commerce AI</button></div><label>Product family<select name="category"><option value="">Help me explore</option>${Object.entries(categories).map(([id,name])=>`<option value="${id}">${name}</option>`).join('')}</select></label><label>Project stage (optional)<select name="project_stage"><option value="">Not decided</option><option>I’m developing my first product</option><option>I’m planning a larger retail range</option></select></label><label>Target market<input name="market" placeholder="e.g. UK retail / US ecommerce"></label><label>Approximate quantity (optional)<input name="quantity" placeholder="e.g. 500 units or still exploring"></label><div class="ask-actions"><button type="button" class="ask-primary" id="ask-next">Continue →</button></div></div><div class="ask-step" data-step="2" hidden><label>Your name<input name="name" required autocomplete="name"></label><label>Work email<input name="email" type="email" required autocomplete="email"></label><label>Company / brand (optional)<input name="company" autocomplete="organization"></label><label>What do you need help with?<textarea name="brief" required placeholder="A product idea, sourcing brief or workflow you want to improve."></textarea></label><div class="ask-actions"><button type="button" class="ask-back">Back</button><button type="submit" class="ask-primary">Download brief ↓</button></div></div><button type="button" class="ask-full">Use full project brief →</button><p class="ask-status" role="status"></p><p class="ask-intro">This preview prepares a local brief. It does not send an enquiry.</p></form>`;
document.body.append(launcher,panel);let collisionPending=false;function keepActionsClear(){collisionPending=false;if(!panel.hidden){launcher.classList.remove('is-obstructing');return}const box=launcher.getBoundingClientRect();const overlap=[...document.querySelectorAll('main .button, main .text-button, footer a, .motion-toggle')].some(el=>{const r=el.getBoundingClientRect();return r.width&&r.height&&r.left<box.right+8&&r.right>box.left-8&&r.top<box.bottom+8&&r.bottom>box.top-8});launcher.classList.toggle('is-obstructing',overlap)}function scheduleClear(){if(!collisionPending){collisionPending=true;requestAnimationFrame(keepActionsClear)}}window.addEventListener('scroll',scheduleClear,{passive:true});window.addEventListener('resize',scheduleClear);document.addEventListener('click',scheduleClear);scheduleClear();let topic='Product sourcing';const form=panel.querySelector('form');const steps=panel.querySelectorAll('.ask-step');
function open(value){panel.hidden=!value;launcher.setAttribute('aria-expanded',String(value));if(value)panel.querySelector('.ask-close').focus();else launcher.focus()}
launcher.addEventListener('click',()=>open(panel.hidden));panel.querySelector('.ask-close').addEventListener('click',()=>open(false));document.addEventListener('keydown',e=>{if(e.key==='Escape'&&!panel.hidden)open(false)});
function step(number){steps.forEach(s=>s.hidden=s.dataset.step!==String(number));panel.querySelector(`[data-step="${number}"] input`)?.focus()}
panel.querySelectorAll('[data-topic]').forEach(button=>button.addEventListener('click',()=>{topic=button.dataset.topic;panel.querySelectorAll('[data-topic]').forEach(b=>b.setAttribute('aria-pressed',String(b===button)));form.elements.quantity.closest('label').hidden=topic==='Commerce AI';form.elements.category.closest('label').hidden=topic==='Commerce AI'}));
panel.querySelector('#ask-next').addEventListener('click',()=>step(2));panel.querySelector('.ask-back').addEventListener('click',()=>step(1));
function data(){return {...Object.fromEntries(new FormData(form)),topic}}
panel.querySelector('.ask-full').addEventListener('click',()=>{const d=data();try{sessionStorage.setItem('able_enquiry_handoff',JSON.stringify(d))}catch{}const target=topic==='Commerce AI'?'commerce-ai.html':'index.html';if(location.pathname.endsWith('/'+target)){applyBrief(d);try{sessionStorage.removeItem('able_enquiry_handoff')}catch{}open(false);document.querySelector(topic==='Commerce AI'?'#contact':'#brief')?.scrollIntoView({behavior:'smooth'})}else location.href=target+(topic==='Commerce AI'?'#contact':'#brief')});
form.addEventListener('submit',event=>{event.preventDefault();if(!form.reportValidity())return;const d=data(),ctx=enquiryContext();const content=`ABLE PROJECT BRIEF\n\nTopic: ${d.topic}\nProject stage: ${d.project_stage||'Not decided'}\nProduct family: ${categories[d.category]||'To explore'}\nMarket: ${d.market||'Not supplied'}\nQuantity: ${d.quantity||'Not supplied'}\nName: ${d.name}\nEmail: ${d.email}\nCompany: ${d.company||'Not supplied'}\nSource page: ${ctx.source_page}\nUTM source: ${ctx.utm_source||'Not supplied'}\nUTM medium: ${ctx.utm_medium||'Not supplied'}\nUTM campaign: ${ctx.utm_campaign||'Not supplied'}\nPrepared at: ${ctx.submitted_at}\n\nBrief:\n${d.brief}\n\nPrepared locally; not submitted.\n`;const url=URL.createObjectURL(new Blob([content],{type:'text/plain;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='able-project-enquiry.txt';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);panel.querySelector('.ask-status').textContent='Brief downloaded. Nothing has been sent. You can also move these details into the full project brief.'});
})();
